In [2]:
import torch
import torch.nn as nn

class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__() #Model is a sub class becuase it is calling the fetuares of the nn.Module so with th help of super keywrod we are calling the init function of the Module class which is the super class
    self.linear=nn.Linear(num_features,1) #bracket me inpout me num_fetaures and output me 1 output
    self.sigmoid=nn.Sigmoid()

  def forward(self,features):
    out=self.linear(features)
    out=self.sigmoid(out)
    return out

In [3]:
features=torch.rand(10,5)
model=Model( features.shape[1] )
model(features)

tensor([[0.5269],
        [0.6172],
        [0.5190],
        [0.5017],
        [0.5195],
        [0.4864],
        [0.5001],
        [0.5871],
        [0.5498],
        [0.5312]], grad_fn=<SigmoidBackward0>)

In [4]:
model.linear.weight

Parameter containing:
tensor([[-0.2687, -0.1053,  0.0649,  0.3492,  0.1952]], requires_grad=True)

In [5]:
model.linear.bias

Parameter containing:
tensor([0.0484], requires_grad=True)

In [6]:
!pip install torchinfo

In [7]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

##neural netwrok with 1 hidden layer

In [8]:
import torch
import torch.nn as nn

class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__() #Model is a sub class becuase it is calling the fetuares of the nn.Module so with th help of super keywrod we are calling the init function of the Module class which is the super class
    self.linear1=nn.Linear(num_features,3) #bracket me inpout me num_fetaures and output me 1 output
    self.relu=nn.ReLU()
    self.linear2=nn.Linear(3,1)
    self.sigmoid=nn.Sigmoid()

  def forward(self,features):
    out=self.linear1(features)
    out=self.relu(out)
    out=self.linear2(out)
    out=self.sigmoid
    return out

In [9]:
features=torch.rand(10,5)
model=Model( features.shape[1] )
model(features)

Sigmoid()

In [10]:
model.linear1.weight

Parameter containing:
tensor([[-0.1543,  0.4319, -0.1895, -0.1828, -0.2551],
        [-0.0914,  0.1135,  0.2741, -0.1518,  0.2311],
        [-0.0877, -0.4123, -0.0557,  0.3158,  0.1698]], requires_grad=True)

In [11]:
model.linear2.weight

Parameter containing:
tensor([[ 0.2468,  0.4432, -0.2249]], requires_grad=True)

In [13]:
#we have to pass the layers through each and every thing manually so we can do this by simply using the Sequrntial model

import torch
import torch.nn as nn

class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__()
     #Model is a sub class becuase it is calling the fetuares of the nn.Module so with th help of super keywrod we are calling the init function of the Module class which is the super class
    self.network=nn.Sequential(
        nn.Linear(num_features,3), #bracket me inpout me num_fetaures and output me 1 output
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid(),
    )


  def forward(self,features):
    out=self.network(features)

    return out