In [2]:
import torch
print(torch.__version__)

2.11.0+cu128


In [3]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"using gpu :{torch.cuda.get_device_name(0)}")
else:
  print("using cpu becuase gpu not available")

GPU is available
using gpu :Tesla T4


##creating tensors

In [4]:
#using empty
a=torch.empty(2,3) # 2 rows and 3 columns ka tensor dega  and memory me jo values rahege wo dega

In [5]:
#check type
type(a)

torch.Tensor

In [6]:
#using zeroes
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
#using rand
torch.rand(2,3)

tensor([[0.8973, 0.7131, 0.0662],
        [0.5118, 0.1615, 0.9602]])

In [9]:
#using seed
#using random every time give us the random values when we run the notbook so if we want reproducibilty then we must use manual_seed
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [10]:
#using tensor
#it creates the manual tensors
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [11]:
#using arange
torch.arange(1,10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
torch.linspace(1,10,10)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [13]:
torch.eye(5) #thisis the identity matrix which creates a 5*5 matrix and diagonal 1 hoga

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [14]:
torch.full((3,3),5) # here we specify we want 3*3 atrix with every value as 5

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

##tensor shape

In [15]:
x=  torch.tensor([[1,2,3],[4,5,6]])
x.shape

torch.Size([2, 3])

In [16]:
#if i wanrt to craete a tensor of the same shape as of the x containing (2,3) size then we have one function in tensor called empty_like
torch.empty_like(x) #this will create the same size twensor as of x but with different values

tensor([[       197568495616, 7310593858020254331, 3616445622929465956],
        [6067809043725954358, 3761132647598405168, 6500441610553274414]])

In [17]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [18]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [24]:
torch.rand_like(x,dtype=torch.float32) # we ned to specify explicitl the datatype because random give the random number in float and x is in integere

tensor([[0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739]])

##tensor data type

In [19]:
x.dtype

torch.int64

In [20]:
#assign the dtype
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [22]:
#using to function we can change the datatype of the existing one
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

##mathematical tensor operation

In [25]:
x=torch.rand(2,2)

In [26]:
x

tensor([[0.2666, 0.6274],
        [0.2696, 0.4414]])

In [27]:
#addition
x+2

tensor([[2.2666, 2.6274],
        [2.2696, 2.4414]])

In [28]:
#subtraction
x-2

tensor([[-1.7334, -1.3726],
        [-1.7304, -1.5586]])

In [29]:
#multilication
x*2

tensor([[0.5332, 1.2549],
        [0.5393, 0.8827]])

In [30]:
x/2

tensor([[0.1333, 0.3137],
        [0.1348, 0.2207]])

In [32]:
#integer division
#it means keeping only the whole numbe and discarding the point numbers
(x*100)//2

tensor([[13., 31.],
        [13., 22.]])

In [33]:
x%2

tensor([[0.2666, 0.6274],
        [0.2696, 0.4414]])

In [34]:
x**2

tensor([[0.0711, 0.3937],
        [0.0727, 0.1948]])

## element wise operation

In [35]:
a=torch.rand(2,3)
b=torch.rand(2,3)

In [36]:
#addtion
a+b

tensor([[0.8441, 0.8378, 1.0569],
        [0.3448, 1.2448, 0.7826]])

In [37]:
#subtraction
a-b

tensor([[-0.2503,  0.8255, -0.8462],
        [ 0.1942, -0.5272, -0.3838]])

In [38]:
a*b

tensor([[0.1625, 0.0051, 0.1002],
        [0.0203, 0.3179, 0.1163]])

In [39]:
a/b

tensor([[5.4263e-01, 1.3500e+02, 1.1068e-01],
        [3.5806e+00, 4.0497e-01, 3.4184e-01]])

In [40]:
a**b

tensor([[0.5146, 0.9989, 0.1174],
        [0.9060, 0.4033, 0.3904]])

In [41]:
a%b

tensor([[2.9692e-01, 2.6345e-05, 1.0531e-01],
        [4.3697e-02, 3.5881e-01, 1.9936e-01]])

In [42]:
c=torch.tensor([1,-2,-3,-4])
torch.abs(c)

tensor([1, 2, 3, 4])

In [43]:
torch.neg(c)

tensor([-1,  2,  3,  4])

In [44]:
torch.round(a)

tensor([[0., 1., 0.],
        [0., 0., 0.]])

In [45]:
torch.ceil(a)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [46]:
torch.floor(a)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [47]:
#clamp keops the vector in the certain range
d=torch.tensor([1.9,2.0])
torch.clamp(d,min=1,max=3)

tensor([1.9000, 2.0000])

##reduction operation

In [56]:
e=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)

In [68]:
e

tensor([[7., 3., 3.],
        [4., 3., 7.]])

In [69]:
torch.sum(e)

tensor(27.)

In [70]:
torch.sum(e,dim=0)

tensor([11.,  6., 10.])

In [71]:
torch.sum(e,dim=1)

tensor([13., 14.])

In [72]:
torch.mean(e)

tensor(4.5000)

In [73]:
torch.mean(e,dim=0)

tensor([5.5000, 3.0000, 5.0000])

In [74]:
torch.median(e)

tensor(3.)

In [75]:
torch.max(e)

tensor(7.)

In [76]:
torch.min(e)

tensor(3.)

In [77]:
torch.prod(e)

tensor(5292.)

In [78]:
torch.std(e)

tensor(1.9748)

In [79]:
torch.var(e)

tensor(3.9000)

In [80]:
torch.argmax(e)

tensor(0)

In [81]:
torch.argmin(e)

tensor(1)

##matrix operation

In [82]:
f=torch.randint(size=(2,3),low=0,high=10)
g=torch.randint(size=(3,2),low=0,high=10)

In [83]:
#matrix multiplication
torch.matmul(f,g)

tensor([[ 72,  72],
        [147,  84]])

In [84]:
vector1=torch.tensor([1,2,3])
vector2=torch.tensor([4,5,6])
torch.dot(vector1,vector2)

tensor(32)

In [85]:
torch.transpose(f,0,1) #want to swaps the dimension 0 with 1

tensor([[0, 9],
        [9, 6],
        [0, 9]])

##comparison operation

In [88]:
i=torch.randint(size=(2,3),low=0,high=10)
j=torch.randint(size=(2,3),low=0,high=10)

In [89]:
i>j

tensor([[False, False, False],
        [False, False, False]])

In [90]:
i<j

tensor([[True, True, True],
        [True, True, True]])

In [92]:
i==j

tensor([[True, True, True],
        [True, True, True]])

In [93]:
i<=j

tensor([[True, True, True],
        [True, True, True]])

In [94]:
i>=j

tensor([[True, True, True],
        [True, True, True]])

##special functions

In [100]:
k=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)

In [101]:
torch.log(k)

tensor([[1.3863, 0.0000, 1.7918],
        [1.0986, 0.6931,   -inf]])

In [102]:
torch.exp(k)

tensor([[ 54.5981,   2.7183, 403.4288],
        [ 20.0855,   7.3891,   1.0000]])

In [103]:
torch.sqrt(k)

tensor([[2.0000, 1.0000, 2.4495],
        [1.7321, 1.4142, 0.0000]])

In [104]:
torch.sigmoid(k)

tensor([[0.9820, 0.7311, 0.9975],
        [0.9526, 0.8808, 0.5000]])

In [105]:
torch.softmax(k,dim=0)

tensor([[0.7311, 0.2689, 0.9975],
        [0.2689, 0.7311, 0.0025]])

In [106]:
torch.relu(k)

tensor([[4., 1., 6.],
        [3., 2., 0.]])

##inplace operation

In [108]:
#koi bhi 2 tensor ka kuch bhi operation kiye to wo new tensor me store hota that means it takes the memory and we dont want that because in some places it might
#take huge amount of memory so for that we have the function we underscore
m=torch.randint(size=(2,2),low=0,high=10)
n=torch.randint(size=(2,2),low=0,high=10)

In [109]:
m.add_(n) #this wil perform the addition operation but it will save the chnages in the m varaible at that particular memory and will not occupy the different memory

tensor([[16, 15],
        [10, 12]])

In [110]:
m.relu_() #uderscore represent the inplace

tensor([[16, 15],
        [10, 12]])

##copying the tensor

In [113]:
o=m.clone()
#clone() function new memoery pe new tensor cretae karta and if we make any chnages in the original one it doesnt affcet the copied one
#assignmnet operation ke sath bhi clone kar skate but it will actaully amke change s inthe copy if we do any of them in the original

##tensor operation on gpu

In [114]:
torch.cuda.is_available()

True

In [115]:
device=torch.device('cuda')

In [116]:
torch.rand(size=(2,3),device=device)

tensor([[0.6130, 0.0101, 0.3984],
        [0.0403, 0.1563, 0.4825]], device='cuda:0')

In [119]:
#existing tensor on the cpu ko agar move karnay gou pe then we have the dunction to()
b=a.to(device)

In [120]:
b+5

tensor([[5.2969, 5.8317, 5.1053],
        [5.2695, 5.3588, 5.1994]], device='cuda:0')

##reshape

In [125]:
m.shape

torch.Size([2, 2])

In [127]:
m.reshape(2,2)

tensor([[16, 15],
        [10, 12]])

In [128]:
m.flatten()

tensor([16, 15, 10, 12])